baseURL = "https://3alkan.github.io/dokuntuler/"
title = "Döküntüler"
languageCode = "tr"
defaultContentLanguage = "tr"
theme = "PaperMod"
enableRobotsTXT = true

[params]
  env = "production"
  title = "Döküntüler"
  description = "Benliğimden dökülenler…"
  keywords = ["blog"]
  author = "Mustafa Alkan"
  hideMeta = false           # show all metadata
  ShowReadingTime = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowWordCount = true
  defaultTheme = "auto"
  hideFooter = false
  showtoc = true
  socialIcons = [
    { name = "github", url = "https://github.com/3alkan" },
    { name = "instagram", url = "https://instagram.com/3alkan" }
  ]


[pagination]
  pagerSize = 10

[menu]
  [[menu.main]]
    name = "Yazılar"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Hakkımda"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Etiketler"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "Ara"
    pageref = "page/search"
    weight = 99


[outputs]
  home = ["HTML", "RSS", "JSON"]
